[project]
name = "billing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jeanpierrebroz", email = "jeanpierrebroz@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
billing = "billing:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
